version: '3'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=S3cret!
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "4000:4000"
volumes:
  db-data:
    driver: local
